require('../../../../bower_components/bootstrap-modal/css/bootstrap-modal.css')
require('../../../../bower_components/brandimint-xediatable-bootstrap/css/bootstrap-editable.css')
require('../../../../bower_components/jquery-ui/themes/smoothness/jquery-ui.css')
require('../../../../bower_components/jquery-simplecolorpicker/jquery.simplecolorpicker.css')

require('jquery.simplecolorpicker')
require('bootstrap-tooltip')
require('bootstrap-popover')
require('bootstrap-editable')
require('jquery.ui.core')
require('jquery.ui.widget')
require('jquery.ui.mouse')
require('jquery.ui.slider')
require('jquery.ui.sortable')
require('bootstrap-modalmanager')
require('bootstrap-modal')
require('backbone.bootstrap-modal')
